### ISSUE TITLE
Add linting rules

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/react-mutation-mapper#3]

**Comment by agarun** [comment]
if you are looking for baselines for rules i like [eslint-config-react-app](https://www.npmjs.com/package/eslint-config-react-app), it's really nice to work with or build off of. it would remove most styling rules though, so [prettier](https://github.com/prettier/prettier) or [prettier-standard](https://github.com/sheerun/prettier-standard) could work well for auto-formatting

**Comment by onursumer** [comment]
This repo is moved into cbioportal-frontend monorepo. We should enforce linting there for all packages.
